#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ค้นหาข้อมูลสมาชิกลืมพกบัตร
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbBeautyBuffetPoint")]
	public partial class clsServDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGEN_ST_POINT(GEN_ST_POINT instance);
    partial void UpdateGEN_ST_POINT(GEN_ST_POINT instance);
    partial void DeleteGEN_ST_POINT(GEN_ST_POINT instance);
    partial void InsertPR_POINT(PR_POINT instance);
    partial void UpdatePR_POINT(PR_POINT instance);
    partial void DeletePR_POINT(PR_POINT instance);
    #endregion
		
		public clsServDataDataContext() : 
				base(global::ค้นหาข้อมูลสมาชิกลืมพกบัตร.Properties.Settings.Default.dbBeautyBuffetPointConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public clsServDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clsServDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clsServDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clsServDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GEN_ST_POINT> GEN_ST_POINTs
		{
			get
			{
				return this.GetTable<GEN_ST_POINT>();
			}
		}
		
		public System.Data.Linq.Table<PR_POINT> PR_POINTs
		{
			get
			{
				return this.GetTable<PR_POINT>();
			}
		}
		
		public System.Data.Linq.Table<MV_POS_POINT> MV_POS_POINTs
		{
			get
			{
				return this.GetTable<MV_POS_POINT>();
			}
		}
		
		public System.Data.Linq.Table<PV_EPOINT> PV_EPOINTs
		{
			get
			{
				return this.GetTable<PV_EPOINT>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GEN_ST_POINT")]
	public partial class GEN_ST_POINT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _SCREATE;
		
		private System.Nullable<System.DateTime> _WORKDATE;
		
		private System.Nullable<int> _WH_ID;
		
		private System.Nullable<int> _ST_ID;
		
		private string _CARDID;
		
		private string _PCODE;
		
		private string _C_NO;
		
		private System.Nullable<decimal> _QTY;
		
		private System.Nullable<decimal> _UPOINT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCREATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSCREATEChanged();
    partial void OnWORKDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnWORKDATEChanged();
    partial void OnWH_IDChanging(System.Nullable<int> value);
    partial void OnWH_IDChanged();
    partial void OnST_IDChanging(System.Nullable<int> value);
    partial void OnST_IDChanged();
    partial void OnCARDIDChanging(string value);
    partial void OnCARDIDChanged();
    partial void OnPCODEChanging(string value);
    partial void OnPCODEChanged();
    partial void OnC_NOChanging(string value);
    partial void OnC_NOChanged();
    partial void OnQTYChanging(System.Nullable<decimal> value);
    partial void OnQTYChanged();
    partial void OnUPOINTChanging(System.Nullable<decimal> value);
    partial void OnUPOINTChanged();
    #endregion
		
		public GEN_ST_POINT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCREATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCREATE
		{
			get
			{
				return this._SCREATE;
			}
			set
			{
				if ((this._SCREATE != value))
				{
					this.OnSCREATEChanging(value);
					this.SendPropertyChanging();
					this._SCREATE = value;
					this.SendPropertyChanged("SCREATE");
					this.OnSCREATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WORKDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> WORKDATE
		{
			get
			{
				return this._WORKDATE;
			}
			set
			{
				if ((this._WORKDATE != value))
				{
					this.OnWORKDATEChanging(value);
					this.SendPropertyChanging();
					this._WORKDATE = value;
					this.SendPropertyChanged("WORKDATE");
					this.OnWORKDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WH_ID", DbType="Int")]
		public System.Nullable<int> WH_ID
		{
			get
			{
				return this._WH_ID;
			}
			set
			{
				if ((this._WH_ID != value))
				{
					this.OnWH_IDChanging(value);
					this.SendPropertyChanging();
					this._WH_ID = value;
					this.SendPropertyChanged("WH_ID");
					this.OnWH_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ST_ID", DbType="Int")]
		public System.Nullable<int> ST_ID
		{
			get
			{
				return this._ST_ID;
			}
			set
			{
				if ((this._ST_ID != value))
				{
					this.OnST_IDChanging(value);
					this.SendPropertyChanging();
					this._ST_ID = value;
					this.SendPropertyChanged("ST_ID");
					this.OnST_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARDID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CARDID
		{
			get
			{
				return this._CARDID;
			}
			set
			{
				if ((this._CARDID != value))
				{
					this.OnCARDIDChanging(value);
					this.SendPropertyChanging();
					this._CARDID = value;
					this.SendPropertyChanged("CARDID");
					this.OnCARDIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PCODE
		{
			get
			{
				return this._PCODE;
			}
			set
			{
				if ((this._PCODE != value))
				{
					this.OnPCODEChanging(value);
					this.SendPropertyChanging();
					this._PCODE = value;
					this.SendPropertyChanged("PCODE");
					this.OnPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_NO", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string C_NO
		{
			get
			{
				return this._C_NO;
			}
			set
			{
				if ((this._C_NO != value))
				{
					this.OnC_NOChanging(value);
					this.SendPropertyChanging();
					this._C_NO = value;
					this.SendPropertyChanged("C_NO");
					this.OnC_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QTY", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> QTY
		{
			get
			{
				return this._QTY;
			}
			set
			{
				if ((this._QTY != value))
				{
					this.OnQTYChanging(value);
					this.SendPropertyChanging();
					this._QTY = value;
					this.SendPropertyChanged("QTY");
					this.OnQTYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPOINT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> UPOINT
		{
			get
			{
				return this._UPOINT;
			}
			set
			{
				if ((this._UPOINT != value))
				{
					this.OnUPOINTChanging(value);
					this.SendPropertyChanging();
					this._UPOINT = value;
					this.SendPropertyChanged("UPOINT");
					this.OnUPOINTChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PR_POINT")]
	public partial class PR_POINT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<System.DateTime> _SCREATE;
		
		private string _UCREATE;
		
		private string _PCODE;
		
		private string _PNAME;
		
		private System.Nullable<System.DateTime> _S_DATE;
		
		private System.Nullable<System.DateTime> _E_DATE;
		
		private string _CTYPE;
		
		private string _S_NO;
		
		private string _E_NO;
		
		private System.Nullable<decimal> _UPOINT;
		
		private System.Nullable<decimal> _DISCAMT;
		
		private string _REMARK;
		
		private System.Nullable<int> _CFLAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSCREATEChanging(System.Nullable<System.DateTime> value);
    partial void OnSCREATEChanged();
    partial void OnUCREATEChanging(string value);
    partial void OnUCREATEChanged();
    partial void OnPCODEChanging(string value);
    partial void OnPCODEChanged();
    partial void OnPNAMEChanging(string value);
    partial void OnPNAMEChanged();
    partial void OnS_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnS_DATEChanged();
    partial void OnE_DATEChanging(System.Nullable<System.DateTime> value);
    partial void OnE_DATEChanged();
    partial void OnCTYPEChanging(string value);
    partial void OnCTYPEChanged();
    partial void OnS_NOChanging(string value);
    partial void OnS_NOChanged();
    partial void OnE_NOChanging(string value);
    partial void OnE_NOChanged();
    partial void OnUPOINTChanging(System.Nullable<decimal> value);
    partial void OnUPOINTChanged();
    partial void OnDISCAMTChanging(System.Nullable<decimal> value);
    partial void OnDISCAMTChanged();
    partial void OnREMARKChanging(string value);
    partial void OnREMARKChanged();
    partial void OnCFLAGChanging(System.Nullable<int> value);
    partial void OnCFLAGChanged();
    #endregion
		
		public PR_POINT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SCREATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> SCREATE
		{
			get
			{
				return this._SCREATE;
			}
			set
			{
				if ((this._SCREATE != value))
				{
					this.OnSCREATEChanging(value);
					this.SendPropertyChanging();
					this._SCREATE = value;
					this.SendPropertyChanged("SCREATE");
					this.OnSCREATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UCREATE", DbType="VarChar(20)")]
		public string UCREATE
		{
			get
			{
				return this._UCREATE;
			}
			set
			{
				if ((this._UCREATE != value))
				{
					this.OnUCREATEChanging(value);
					this.SendPropertyChanging();
					this._UCREATE = value;
					this.SendPropertyChanged("UCREATE");
					this.OnUCREATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PCODE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PCODE
		{
			get
			{
				return this._PCODE;
			}
			set
			{
				if ((this._PCODE != value))
				{
					this.OnPCODEChanging(value);
					this.SendPropertyChanging();
					this._PCODE = value;
					this.SendPropertyChanged("PCODE");
					this.OnPCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PNAME", DbType="VarChar(200)")]
		public string PNAME
		{
			get
			{
				return this._PNAME;
			}
			set
			{
				if ((this._PNAME != value))
				{
					this.OnPNAMEChanging(value);
					this.SendPropertyChanging();
					this._PNAME = value;
					this.SendPropertyChanged("PNAME");
					this.OnPNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> S_DATE
		{
			get
			{
				return this._S_DATE;
			}
			set
			{
				if ((this._S_DATE != value))
				{
					this.OnS_DATEChanging(value);
					this.SendPropertyChanging();
					this._S_DATE = value;
					this.SendPropertyChanged("S_DATE");
					this.OnS_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_DATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> E_DATE
		{
			get
			{
				return this._E_DATE;
			}
			set
			{
				if ((this._E_DATE != value))
				{
					this.OnE_DATEChanging(value);
					this.SendPropertyChanging();
					this._E_DATE = value;
					this.SendPropertyChanged("E_DATE");
					this.OnE_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTYPE", DbType="VarChar(20)")]
		public string CTYPE
		{
			get
			{
				return this._CTYPE;
			}
			set
			{
				if ((this._CTYPE != value))
				{
					this.OnCTYPEChanging(value);
					this.SendPropertyChanging();
					this._CTYPE = value;
					this.SendPropertyChanged("CTYPE");
					this.OnCTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S_NO", DbType="VarChar(20)")]
		public string S_NO
		{
			get
			{
				return this._S_NO;
			}
			set
			{
				if ((this._S_NO != value))
				{
					this.OnS_NOChanging(value);
					this.SendPropertyChanging();
					this._S_NO = value;
					this.SendPropertyChanged("S_NO");
					this.OnS_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_NO", DbType="VarChar(20)")]
		public string E_NO
		{
			get
			{
				return this._E_NO;
			}
			set
			{
				if ((this._E_NO != value))
				{
					this.OnE_NOChanging(value);
					this.SendPropertyChanging();
					this._E_NO = value;
					this.SendPropertyChanged("E_NO");
					this.OnE_NOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UPOINT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> UPOINT
		{
			get
			{
				return this._UPOINT;
			}
			set
			{
				if ((this._UPOINT != value))
				{
					this.OnUPOINTChanging(value);
					this.SendPropertyChanging();
					this._UPOINT = value;
					this.SendPropertyChanged("UPOINT");
					this.OnUPOINTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DISCAMT", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> DISCAMT
		{
			get
			{
				return this._DISCAMT;
			}
			set
			{
				if ((this._DISCAMT != value))
				{
					this.OnDISCAMTChanging(value);
					this.SendPropertyChanging();
					this._DISCAMT = value;
					this.SendPropertyChanged("DISCAMT");
					this.OnDISCAMTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_REMARK", DbType="VarChar(1000)")]
		public string REMARK
		{
			get
			{
				return this._REMARK;
			}
			set
			{
				if ((this._REMARK != value))
				{
					this.OnREMARKChanging(value);
					this.SendPropertyChanging();
					this._REMARK = value;
					this.SendPropertyChanged("REMARK");
					this.OnREMARKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CFLAG", DbType="Int")]
		public System.Nullable<int> CFLAG
		{
			get
			{
				return this._CFLAG;
			}
			set
			{
				if ((this._CFLAG != value))
				{
					this.OnCFLAGChanging(value);
					this.SendPropertyChanging();
					this._CFLAG = value;
					this.SendPropertyChanged("CFLAG");
					this.OnCFLAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MV_POS_POINT")]
	public partial class MV_POS_POINT
	{
		
		private string _CARDID;
		
		private string _CTNAME;
		
		private System.Nullable<System.DateTime> _MAXDATE;
		
		private System.Nullable<decimal> _NET;
		
		private System.Nullable<decimal> _RPOINT;
		
		public MV_POS_POINT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARDID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CARDID
		{
			get
			{
				return this._CARDID;
			}
			set
			{
				if ((this._CARDID != value))
				{
					this._CARDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTNAME", DbType="VarChar(1000)")]
		public string CTNAME
		{
			get
			{
				return this._CTNAME;
			}
			set
			{
				if ((this._CTNAME != value))
				{
					this._CTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAXDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> MAXDATE
		{
			get
			{
				return this._MAXDATE;
			}
			set
			{
				if ((this._MAXDATE != value))
				{
					this._MAXDATE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NET", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> NET
		{
			get
			{
				return this._NET;
			}
			set
			{
				if ((this._NET != value))
				{
					this._NET = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RPOINT", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> RPOINT
		{
			get
			{
				return this._RPOINT;
			}
			set
			{
				if ((this._RPOINT != value))
				{
					this._RPOINT = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PV_EPOINT")]
	public partial class PV_EPOINT
	{
		
		private string _CT_CARDID;
		
		private System.Nullable<decimal> _epoint;
		
		public PV_EPOINT()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CT_CARDID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CT_CARDID
		{
			get
			{
				return this._CT_CARDID;
			}
			set
			{
				if ((this._CT_CARDID != value))
				{
					this._CT_CARDID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_epoint", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> epoint
		{
			get
			{
				return this._epoint;
			}
			set
			{
				if ((this._epoint != value))
				{
					this._epoint = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
