#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchCustom
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dbMona")]
	public partial class clsHBDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMK_DOC_HBD(MK_DOC_HBD instance);
    partial void UpdateMK_DOC_HBD(MK_DOC_HBD instance);
    partial void DeleteMK_DOC_HBD(MK_DOC_HBD instance);
    #endregion
		
		public clsHBDDataContext() : 
				base(global::ค้นหาข้อมูลสมาชิกลืมพกบัตร.Properties.Settings.Default.dbMonaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public clsHBDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clsHBDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clsHBDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public clsHBDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MK_DOC_HBD> MK_DOC_HBDs
		{
			get
			{
				return this.GetTable<MK_DOC_HBD>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MK_DOC_HBD")]
	public partial class MK_DOC_HBD : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _whcode;
		
		private string _abbno;
		
		private System.DateTime _workdate;
		
		private string _cardno;
		
		private string _cardtype;
		
		private string _stcode;
		
		private System.Nullable<decimal> _qty;
		
		private System.Nullable<decimal> _amt;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnwhcodeChanging(string value);
    partial void OnwhcodeChanged();
    partial void OnabbnoChanging(string value);
    partial void OnabbnoChanged();
    partial void OnworkdateChanging(System.DateTime value);
    partial void OnworkdateChanged();
    partial void OncardnoChanging(string value);
    partial void OncardnoChanged();
    partial void OncardtypeChanging(string value);
    partial void OncardtypeChanged();
    partial void OnstcodeChanging(string value);
    partial void OnstcodeChanged();
    partial void OnqtyChanging(System.Nullable<decimal> value);
    partial void OnqtyChanged();
    partial void OnamtChanging(System.Nullable<decimal> value);
    partial void OnamtChanged();
    #endregion
		
		public MK_DOC_HBD()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_whcode", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string whcode
		{
			get
			{
				return this._whcode;
			}
			set
			{
				if ((this._whcode != value))
				{
					this.OnwhcodeChanging(value);
					this.SendPropertyChanging();
					this._whcode = value;
					this.SendPropertyChanged("whcode");
					this.OnwhcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abbno", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string abbno
		{
			get
			{
				return this._abbno;
			}
			set
			{
				if ((this._abbno != value))
				{
					this.OnabbnoChanging(value);
					this.SendPropertyChanging();
					this._abbno = value;
					this.SendPropertyChanged("abbno");
					this.OnabbnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workdate", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime workdate
		{
			get
			{
				return this._workdate;
			}
			set
			{
				if ((this._workdate != value))
				{
					this.OnworkdateChanging(value);
					this.SendPropertyChanging();
					this._workdate = value;
					this.SendPropertyChanged("workdate");
					this.OnworkdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardno", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string cardno
		{
			get
			{
				return this._cardno;
			}
			set
			{
				if ((this._cardno != value))
				{
					this.OncardnoChanging(value);
					this.SendPropertyChanging();
					this._cardno = value;
					this.SendPropertyChanged("cardno");
					this.OncardnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cardtype", DbType="VarChar(20)")]
		public string cardtype
		{
			get
			{
				return this._cardtype;
			}
			set
			{
				if ((this._cardtype != value))
				{
					this.OncardtypeChanging(value);
					this.SendPropertyChanging();
					this._cardtype = value;
					this.SendPropertyChanged("cardtype");
					this.OncardtypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stcode", DbType="VarChar(20)")]
		public string stcode
		{
			get
			{
				return this._stcode;
			}
			set
			{
				if ((this._stcode != value))
				{
					this.OnstcodeChanging(value);
					this.SendPropertyChanging();
					this._stcode = value;
					this.SendPropertyChanged("stcode");
					this.OnstcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qty", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> qty
		{
			get
			{
				return this._qty;
			}
			set
			{
				if ((this._qty != value))
				{
					this.OnqtyChanging(value);
					this.SendPropertyChanging();
					this._qty = value;
					this.SendPropertyChanged("qty");
					this.OnqtyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amt", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> amt
		{
			get
			{
				return this._amt;
			}
			set
			{
				if ((this._amt != value))
				{
					this.OnamtChanging(value);
					this.SendPropertyChanging();
					this._amt = value;
					this.SendPropertyChanged("amt");
					this.OnamtChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
